# .github/workflows/generate-snake.yml
name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # executa diariamente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: devlucasrezende
          outputs: |
            ./output/snake.svg

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
